application: matasz-jelenlet
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /scripts
  static_dir: scripts
- url: /images
  static_dir: images
- url: /flash
  static_dir: flash
- url: /.*
  script: main.py
